# simulazione di un sitema monty-hall 


3 outcomes : 2 negativi , 1 positivo


In [67]:
import numpy as np
from matplotlib import pyplot as plt
from scipy import stats


1000
0.336


scelta casuale porta 

In [32]:
import numpy as np
from matplotlib import pyplot as plt
from scipy import stats
s=0
r=0
n=10
for i in range(n):
 rd= np.random.randint(0,3)
 d=[0,0,0]
 d[rd]=1 
 rc=np.random.randint(0,3)
 d1=[0,1,2]
 if rc == rd :
        d1= np.delete(d1, np.where(d1 == rd))
        print(d1)
 if rc != rd :
        d1= np.delete(d1, np.where(d1 == rc))
        d1= np.delete(d1, np.where(d1 == rd))
      
 a=d[rc]
 if a==1 :
    s=s+1
 b=d[mp]
 if b==1 :
    r=r+1
print(n)
print(s/n)   
print(r/n)

[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
10
0.4
0.4


In [31]:
d1= np.delete(d1, np.where(d1 == rc))
print(d1)

[0]
